#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: redis
#  namespace: argocd
#  argocd.argoproj.io/sync-wave: "3"
#spec:
#  project: default
#  source:
#    repoURL: 'https://charts.bitnami.com/bitnami'
#    targetRevision: 11.1.0
#    chart: redis
#    helm:
#      parameters:
#        - name: "cluster.enabled"
#          value: "false"
#        - name: "cluster.slaveCount"
#          value: "0"
#        - name: "usePassword"
#          value: "false"
#        - name: "master.persistence.enabled"
#          value: "false"
#  destination:
#    server: 'https://kubernetes.default.svc'
#    namespace: demo
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
