apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins
    role: master
  name: jenkins-master-data-pvc
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 8Gi
  storageClassName: jenkins-master
  volumeMode: Filesystem
  volumeName: jenkins-master-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
