apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: jenkins-master
  volumeMode: Filesystem
  local:
    path: /var/opt/jenkins-master-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-demo-2.devopsua.tk